Events
BroncoBond/Bronco-Bond pull request #58
Opened 2024-08-02 23:06 UTC by PlainOlSoapBar

- Events can either be public or private.
- Event hosts can be assigned to any person or organization, regardless if they exist in BroncoBond. 
  - By default, the event host will be set as the event creator (username).
# Public Events
- Can be created only by administrators.
- Can be edited or deleted only by the event creator.
- Can be searched for by users.
- Users can express interest in these events.
# Private Events
- Can be created by anyone.
- Can be edited and deleted only by the event creator. 
- Administrators can delete any private event.

2024-08-03 18:31 UTC, monsothin96 commented
Jay-Branch

2024-08-09 06:34 UTC, Jayvnn commented on backends/controller/event.controller.js
When updating event, check if the new event start date time is after the current date time.

2024-08-09 06:35 UTC, Jayvnn commented on backends/controller/event.controller.js
Also during the updating event, check if the new start date time and new end date time are appropriate before creating the model.

2024-08-09 06:44 UTC, Jayvnn commented on backends/controller/event.controller.js
When deleting event first check the type of event, then organize code by if event is private or public

2024-08-09 06:50 UTC, Jayvnn requested changes
Check comments on needed changes

2024-08-10 07:30 UTC, Jayvnn approved these changes

2024-08-10 07:30 UTC, merged